name: Evitar Pausa do Supabase

on:
  schedule:
    # comando cron para rodar à meia-noite, a cada 4 dias
    - cron: '0 0 */4 * *'
  # permitir rodar o script manualmente no github
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping na API do Supabase
        # comando curl para fazer uma requisição rápida apenas para o Supabase registrar atividade
        run: curl -s "https://xfuckzfjyjddizzltxmq.supabase.co/auth/v1/health"